---
title: "Assignment 7"
author: "Darren Jeng"
date: "November 4, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(broom)
library(choroplethr)
library(rvest)
```

## Maternal mortality tidy 

```{r cars}
# Reading csv file from my github
Mortal <- read.csv("https://raw.githubusercontent.com/KaiJeng/AssignmentSeven/master/data/xmart.csv")
names(Mortal) <- make.names(names(Mortal))
names(Mortal)[3] <- "Maternal.Mortality.Ratio"
names(Mortal)[4] <- "Birth.Attend.Percentage"

# Create and clean new variables
Mortal$lower_bound <- str_extract_all(Mortal$Maternal.Mortality.Ratio,"\\[[0-9]? [0-9]+")
Mortal$lower_bound <- str_replace_all(Mortal$lower_bound,"\\[ ","")
Mortal$lower_bound <- str_replace_all(Mortal$lower_bound,"\\[","")
Mortal$lower_bound <- str_replace_all(Mortal$lower_bound," ","")
Mortal$lower_bound <- as.numeric(Mortal$lower_bound)
Mortal$lower_bound[is.na(Mortal$lower_bound)] <- 0

Mortal$upper_bound <- str_extract_all(Mortal$Maternal.Mortality.Ratio,"[0-9]? [0-9]+\\]$")
Mortal$upper_bound <- str_replace_all(Mortal$upper_bound," ","")
Mortal$upper_bound <- str_replace_all(Mortal$upper_bound,"\\]","")
Mortal$upper_bound <- as.numeric(Mortal$upper_bound)
Mortal$upper_bound[is.na(Mortal$upper_bound)] <- 0

Mortal$Mortality <- str_extract_all(Mortal$Maternal.Mortality.Ratio,"^[0-9]? ?[0-9]+")
Mortal$Mortality <- str_replace_all(Mortal$Mortality," ","")
Mortal$Mortality <- as.numeric(Mortal$Mortality)
Mortal$Mortality[is.na(Mortal$Mortality)] <- 0
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
 Income <- read.csv("https://raw.githubusercontent.com/KaiJeng/AssignmentSeven/master/data/WHS9_93.csv")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
